In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("campeonato-brasileiro-full.csv")

In [3]:
df.head()

,ID,Rodada,Data,Horário,Dia,Mandante,Visitante,Vencedor,Arena,Mandante Placar,Visitante Placar,Estado Mandante,Estado Visitante,Estado Vencedor
0,1,1,2000-07-29,16h00,Sábado,Fluminense,Bahia,Fluminense,Maracanã,2,0,RJ,BA,RJ
1,2,1,2000-07-29,16h00,Sábado,Vasco,Sport,Sport,São Januário,0,2,RJ,PE,PE
2,3,1,2000-07-29,16h00,Sábado,Vitória,Palmeiras,Vitória,Barradão,4,1,ES,SP,ES
3,4,1,2000-07-30,17h00,Domingo,Botafogo-RJ,Atlético-MG,-,Caio Martins,0,0,RJ,MG,-
4,5,1,2000-07-30,18h30,Domingo,Juventude,Flamengo,-,Alfredo Jaconi,1,1,RS,RJ,-

In [4]:
# Mostra todas as ocorrencia "Sabado"  na coluna 'Dia':
sab = df.Dia == 'Sábado'
saturday = sab.count()
print(saturday)

8319

In [5]:
# OU
# Mostra False ou True De acordo com cada coluna:
df.Dia == 'Sábado'

0        True
1        True
2        True
3       False
4       False
        ...
8314    False
8315    False
8316    False
8317    False
8318    False
Name: Dia, Length: 8319, dtype: bool

In [6]:
# Filtro:
quarta = 0
sabado = 0
for I in df.Dia:
    if 'Quarta-feira' in I:
        quarta += 1
    elif I == 'Sábado':
        sabado += 1
        #print(I)

print(f'Quartas Feiras: {quarta}\nSabados: {sabado}')

Quartas Feiras: 1559
Sabados: 1925

In [7]:
# MOSTRA A TABELA INTEIRA, PORÉM NA COLUNA 'Visitante' , Só a ocorrencia
#.. 'Bahia' :

df[df.Visitante == "Bahia"]

,ID,Rodada,Data,Horário,Dia,Mandante,Visitante,Vencedor,Arena,Mandante Placar,Visitante Placar,Estado Mandante,Estado Visitante,Estado Vencedor
0,1,1,2000-07-29,16h00,Sábado,Fluminense,Bahia,Fluminense,Maracanã,2,0,RJ,BA,RJ
20,21,3,2000-08-06,16h00,Domingo,Atlético-MG,Bahia,-,Mineirão,0,0,MG,BA,-
52,53,7,2000-08-16,20h30,Quarta-feira,Gama,Bahia,Bahia,Mané Garrincha,0,1,DF,BA,BA
63,64,8,2000-08-20,17h00,Domingo,São Paulo,Bahia,-,Morumbi,1,1,SP,BA,-
92,93,12,2000-09-02,15h45,Sábado,Coritiba,Bahia,-,Couto Pereira,1,1,PR,BA,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8225,8226,29,2021-01-10,18:15,Domingo,Atlético-GO,Bahia,-,Antônio Accioly,1,1,GO,BA,-
8255,8256,32,2021-01-24,18:15,Domingo,Sport,Bahia,Sport,Ilha do Retiro,2,0,PE,BA,PE
8259,8260,33,2021-01-31,16:00,Domingo,Vasco,Bahia,-,São Januário,0,0,RJ,BA,-
8291,8292,36,2021-02-13,19:00,Sábado,Atlético-MG,Bahia,-,Mineirão,1,1,MG,BA,-
8300,8301,37,2021-02-20,21:00,Sábado,Fortaleza,Bahia,Bahia,Castelão,0,4,CE,BA,BA

In [8]:
# iloc  ==  Numeros
# loc   ==  Strings

# TRAZENDO APENAS QUANDO O 'SPORT' JOGOU, E QUAL FOI A ARENA:
# Do lado esquerdo esta o Indice de quando ocorre:

Sport_Arena = df.loc[df.Visitante == 'Sport', 'Arena']
display(Sport_Arena)

1                   São Januário
9                  Couto Pereira
66                Alfredo Jaconi
101                     Barradão
109          Olímpico Monumental
                  ...
8230    Nilton Santos (Engenhão)
8248           Neo Química Arena
8277    Nilton Santos (Engenhão)
8283                   Beira Rio
8316            Arena da Baixada
Name: Arena, Length: 215, dtype: object

In [9]:
mandante_vasco = df.Mandante == 'Vasco'
mandante_vasco

0       False
1        True
2       False
3       False
4       False
        ...
8314    False
8315    False
8316    False
8317    False
8318    False
Name: Mandante, Length: 8319, dtype: bool

In [10]:
# CRIAMOS UM DATAFRAME ONDE SÓ DE MOSTRA AS OCORRENCIAS 'VASCO' NA COLNA MANDANTE:
df_mandante_vasco = df.loc[mandante_vasco]
df_mandante_vasco

,ID,Rodada,Data,Horário,Dia,Mandante,Visitante,Vencedor,Arena,Mandante Placar,Visitante Placar,Estado Mandante,Estado Visitante,Estado Vencedor
1,2,1,2000-07-29,16h00,Sábado,Vasco,Sport,Sport,São Januário,0,2,RJ,PE,PE
21,22,3,2000-08-06,17h00,Domingo,Vasco,Cruzeiro,-,São Januário,3,3,RJ,MG,-
37,38,5,2000-08-11,20h30,Sexta-feira,Vasco,Corinthians,Vasco,São Januário,1,0,RJ,SP,RJ
68,69,8,2000-08-20,17h00,Domingo,Vasco,Ponte Preta,Vasco,São Januário,2,1,RJ,SP,RJ
102,103,13,2000-09-05,20h30,Terça-feira,Vasco,Athlético-PR,-,São Januário,2,2,RJ,PR,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8231,8232,30,2021-01-16,21:00,Sábado,Vasco,Coritiba,Coritiba,São Januário,0,1,RJ,PR,PR
8250,8251,32,2021-01-23,21:00,Sábado,Vasco,Atlético-MG,Vasco,São Januário,3,2,RJ,MG,RJ
8259,8260,33,2021-01-31,16:00,Domingo,Vasco,Bahia,-,São Januário,0,0,RJ,BA,-
8293,8294,36,2021-02-14,16:00,Domingo,Vasco,Internacional,Internacional,São Januário,0,2,RJ,RS,RS
8310,8311,38,2021-02-25,21:30,Quinta-Feira,Vasco,Goiás,Vasco,São Januário,3,2,RJ,GO,RJ

In [14]:
# MOSTRA A INCIDENCIA DE 'Vasco' na Coluna 'Mandante' , com True ou False:
mandante_vasco = df.Mandante == "Vasco"
mandante_vasco.head()

0    False
1     True
2    False
3    False
4    False
Name: Mandante, dtype: bool

In [25]:
# NO CASO O NOME DA COLUNA CONTÉM ESPAÇO EM BRNACO, ASSIM DEVEMOS NOS
#.. REFERIR A ELA COMO UMA STRING PARA FAZER AS CONSULTAS:


# PEGANDO SOMENTE ONDE O PLACAR FOI MAIOR QUE 2 :
mandante_placar = df["Mandante Placar"] > 2

#mandante_placar.head()

print('Total de Partidas: ',len(mandante_placar))  # 8319

contar = 0
for I in mandante_placar:
    if I == True:
        contar+=1
print('Com mais de 2 gols: ',contar)

# NUM TOTAL DE 8319 PARTIDAS, APENAS 1764 TIVERAM O PLACAR A CIMA DE 2 GOLS.

Total de Partidas:  8319
Com mais de 2 gols:  1761

In [26]:
#  &  é o mesmo que 'and'  :
(mandante_vasco & mandante_placar).head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [28]:
df_vasco_placar = df.loc[mandante_vasco & mandante_placar, ['Data', "Horário","Dia"]]

In [29]:
# VEZES EM QUE O VASCO ERA O MANDANTE E FEZ MAIS DE 2 GOLS:
df_vasco_placar.head()

           Data Horário           Dia
21   2000-08-06   17h00       Domingo
127  2000-09-13   20h30  Quarta-feira
147  2000-09-20   22h00  Quarta-feira
180  2000-10-04   20h30  Quarta-feira
357  2001-08-05   14h30       Domingo

In [32]:
df_vasco_placar.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 64 entries, 21 to 8310
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Data     64 non-null     object
 1   Horário  62 non-null     object
 2   Dia      64 non-null     object
dtypes: object(3)
memory usage: 2.0+ KB

ola mundo