In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("campeonato-brasileiro-full.csv")

In [3]:
df.head()

,ID,Rodada,Data,Horário,Dia,Mandante,Visitante,Vencedor,Arena,Mandante Placar,Visitante Placar,Estado Mandante,Estado Visitante,Estado Vencedor
0,1,1,2000-07-29,16h00,Sábado,Fluminense,Bahia,Fluminense,Maracanã,2,0,RJ,BA,RJ
1,2,1,2000-07-29,16h00,Sábado,Vasco,Sport,Sport,São Januário,0,2,RJ,PE,PE
2,3,1,2000-07-29,16h00,Sábado,Vitória,Palmeiras,Vitória,Barradão,4,1,ES,SP,ES
3,4,1,2000-07-30,17h00,Domingo,Botafogo-RJ,Atlético-MG,-,Caio Martins,0,0,RJ,MG,-
4,5,1,2000-07-30,18h30,Domingo,Juventude,Flamengo,-,Alfredo Jaconi,1,1,RS,RJ,-

In [5]:
# CRIANDO UMA NOVA COLUNA NO DF -> COLUNA 'PAIS' Com todas as
#..linhas preenchidas com ->'BRAISL' :

df['Pais'] = 'Braisl'

In [7]:
df.head()

,ID,Rodada,Data,Horário,Dia,Mandante,Visitante,Vencedor,Arena,Mandante Placar,Visitante Placar,Estado Mandante,Estado Visitante,Estado Vencedor,Páis,Pais
0,1,1,2000-07-29,16h00,Sábado,Fluminense,Bahia,Fluminense,Maracanã,2,0,RJ,BA,RJ,Braisl,Braisl
1,2,1,2000-07-29,16h00,Sábado,Vasco,Sport,Sport,São Januário,0,2,RJ,PE,PE,Braisl,Braisl
2,3,1,2000-07-29,16h00,Sábado,Vitória,Palmeiras,Vitória,Barradão,4,1,ES,SP,ES,Braisl,Braisl
3,4,1,2000-07-30,17h00,Domingo,Botafogo-RJ,Atlético-MG,-,Caio Martins,0,0,RJ,MG,-,Braisl,Braisl
4,5,1,2000-07-30,18h30,Domingo,Juventude,Flamengo,-,Alfredo Jaconi,1,1,RS,RJ,-,Braisl,Braisl

In [8]:
# NOVA COLUNA PREENCHIDA COM O NUMERO 2 :
df['Coluna_Nova'] = 2


# EXATAMENTE COMO NUM DICIONARIO -> CHAVE | VALOR:
# d1 = []
# d1['dummy'] = 'Outro valor'

In [10]:
df.head()

,ID,Rodada,Data,Horário,Dia,Mandante,Visitante,Vencedor,Arena,Mandante Placar,Visitante Placar,Estado Mandante,Estado Visitante,Estado Vencedor,Páis,Pais,Coluna_Nova
0,1,1,2000-07-29,16h00,Sábado,Fluminense,Bahia,Fluminense,Maracanã,2,0,RJ,BA,RJ,Braisl,Braisl,2
1,2,1,2000-07-29,16h00,Sábado,Vasco,Sport,Sport,São Januário,0,2,RJ,PE,PE,Braisl,Braisl,2
2,3,1,2000-07-29,16h00,Sábado,Vitória,Palmeiras,Vitória,Barradão,4,1,ES,SP,ES,Braisl,Braisl,2
3,4,1,2000-07-30,17h00,Domingo,Botafogo-RJ,Atlético-MG,-,Caio Martins,0,0,RJ,MG,-,Braisl,Braisl,2
4,5,1,2000-07-30,18h30,Domingo,Juventude,Flamengo,-,Alfredo Jaconi,1,1,RS,RJ,-,Braisl,Braisl,2

In [11]:
# CRIA NOVA COLUNA COM O VALOR DA SOMA DE OUTRAS DUAS JÁ EXISTENTES:
df['Gols_Partida'] = df['Mandante Placar'] + df['Visitante Placar']

In [13]:
df[['Gols_Partida']]

      Gols_Partida
0                2
1                2
2                5
3                0
4                2
...            ...
8314             0
8315             2
8316             2
8317             3
8318             4

[8319 rows x 1 columns]

In [14]:
df.head()

,ID,Rodada,Data,Horário,Dia,Mandante,Visitante,Vencedor,Arena,Mandante Placar,Visitante Placar,Estado Mandante,Estado Visitante,Estado Vencedor,Páis,Pais,Coluna_Nova,Gols_Partida
0,1,1,2000-07-29,16h00,Sábado,Fluminense,Bahia,Fluminense,Maracanã,2,0,RJ,BA,RJ,Braisl,Braisl,2,2
1,2,1,2000-07-29,16h00,Sábado,Vasco,Sport,Sport,São Januário,0,2,RJ,PE,PE,Braisl,Braisl,2,2
2,3,1,2000-07-29,16h00,Sábado,Vitória,Palmeiras,Vitória,Barradão,4,1,ES,SP,ES,Braisl,Braisl,2,5
3,4,1,2000-07-30,17h00,Domingo,Botafogo-RJ,Atlético-MG,-,Caio Martins,0,0,RJ,MG,-,Braisl,Braisl,2,0
4,5,1,2000-07-30,18h30,Domingo,Juventude,Flamengo,-,Alfredo Jaconi,1,1,RS,RJ,-,Braisl,Braisl,2,2